### ISSUE TITLE
F-Droid inclusion

### ISSUE THREAD

**Issue by Altonss** [sozialhelden/wheelmap-native-wrapper#14]
F-Droid https://f-droid.org/ is an android app store for free/libre and open source software. I would like to add the wheelmap android app to F-Droid.
F-Droid requires the original author to not oppose the inclusion. Would you be opposed to the inclusion in the free app-store F-Droid?
If you are not opposed, we would need to fix a few issues:
- First you would need to add a license as in #13 
- Second, the F-Droid scanner found many jar files. Are those needed to build the android app?
> Java JAR file: tools/vd-tool/lib/bcprov-jdk15on-1.56.jar
> Java JAR file: tools/vd-tool/lib/guava-23.0.jar
> Java JAR file: tools/vd-tool/lib/javax.inject-1.jar
> Java JAR file: tools/vd-tool/lib/builder-model-3.2.0-dev.jar
> Java JAR file: tools/vd-tool/lib/kotlin-stdlib-common-1.2.71.jar
> Java JAR file: tools/vd-tool/lib/annotations-13.0.jar
> Java JAR file: tools/vd-tool/lib/stax-ex-1.7.7.jar
> Java JAR file: tools/vd-tool/lib/annotations-26.2.0-dev.jar
> Java JAR file: tools/vd-tool/lib/error_prone_annotations-2.0.18.jar
> Java JAR file: tools/vd-tool/lib/bcpkix-jdk15on-1.56.jar
> Java JAR file: tools/vd-tool/lib/kotlin-stdlib-jdk8-1.2.71.jar
> Java JAR file: tools/vd-tool/lib/kotlin-stdlib-1.2.71.jar
> Java JAR file: tools/vd-tool/lib/jimfs-1.1.jar
> Java JAR file: tools/vd-tool/lib/sdklib-26.2.0-dev.jar
> Java JAR file: tools/vd-tool/lib/FastInfoset-1.2.13.jar
> Java JAR file: tools/vd-tool/lib/dvlib-26.2.0-dev.jar
> Java JAR file: tools/vd-tool/lib/kotlin-reflect-1.2.0.jar
> Java JAR file: tools/vd-tool/lib/commons-compress-1.12.jar
> Java JAR file: tools/vd-tool/lib/jaxb-runtime-2.2.11.jar
> Java JAR file: tools/vd-tool/lib/vd-tool.jar
> Java JAR file: tools/vd-tool/lib/builder-test-api-3.2.0-dev.jar
> Java JAR file: tools/vd-tool/lib/repository-26.2.0-dev.jar
> Java JAR file: tools/vd-tool/lib/jsr305-1.3.9.jar
> Java JAR file: tools/vd-tool/lib/j2objc-annotations-1.1.jar
> Java JAR file: tools/vd-tool/lib/jaxb-api-2.2.12-b140109.1041.jar
> Java JAR file: tools/vd-tool/lib/layoutlib-api-26.2.0-dev.jar
> Java JAR file: tools/vd-tool/lib/kotlin-stdlib-jdk7-1.2.71.jar
> Java JAR file: tools/vd-tool/lib/commons-logging-1.2.jar
> Java JAR file: tools/vd-tool/lib/txw2-2.2.11.jar
> Java JAR file: tools/vd-tool/lib/jaxb-core-2.2.11.jar
> Java JAR file: tools/vd-tool/lib/istack-commons-runtime-2.21.jar
> Java JAR file: tools/vd-tool/lib/protobuf-java-3.4.0.jar
> Java JAR file: tools/vd-tool/lib/httpclient-4.5.2.jar
> Java JAR file: tools/vd-tool/lib/gson-2.8.0.jar
> Java JAR file: tools/vd-tool/lib/httpcore-4.4.5.jar
> Java JAR file: tools/vd-tool/lib/common-26.2.0-dev.jar
> Java JAR file: tools/vd-tool/lib/kxml2-2.3.0.jar
> Java JAR file: tools/vd-tool/lib/sdk-common-26.2.0-dev.jar
> Java JAR file: tools/vd-tool/lib/httpmime-4.5.2.jar
> Java JAR file: tools/vd-tool/lib/javax.activation-1.2.0.jar
> Java JAR file: tools/vd-tool/lib/animal-sniffer-annotations-1.14.jar
> Java JAR file: tools/vd-tool/lib/commons-codec-1.9.jar
> Java JAR file: tools/vd-tool/lib/ddmlib-26.2.0-dev.jar

Thanks for your time and for your help :)

**Comment by Altonss** [comment]
Any feedback? (maybe @opyh idk). I'm sorry to bother you with this ^^

**Comment by opyh** [comment]
A few questions:

- Who would maintain the store entry on the long term - you? How much time could you spend per year for maintenance?
- Where is the build created, so people can ensure there is no malware injected? How transparent is the build process?
- To use Wheelmap's CI, the build uses a secret token that it uses to fetch that info from our servers. Would this token be publicly visible?

The vd-tools files are used for creating vector icons from SVG assets.

**Comment by Altonss** [comment]
Here is the request for packaging into F-Droid if you want to take a look: https://gitlab.com/fdroid/rfp/-/issues/1890
If you want to know more about the packaging process of F-Droid you can read the FAQ here: https://f-droid.org/fr/docs/FAQ_-_App_Developers/

> Who would maintain the store entry on the long term - you? How much time could you spend per year for maintenance?

The entry should maintain itself automatically, because F-Droid detects every new tagged release!



> Where is the build created, so people can ensure there is no malware injected? How transparent is the build process?

F-Droid builds directly from source and for more trust it is even possible to enable reproductible builds. (but I'm not an expert so the best is to read the FAQ about this topic).


> To use Wheelmap's CI, the build uses a secret token that it uses to fetch that info from our servers. Would this token be publicly visible?

On this topic I don't know what to answer. Maybe @IzzySoft has a better answer :)

**Comment by IzzySoft** [comment]
You can always read up the details [in my articles here](https://android.izzysoft.de/articles/tagged/fdroid?lang=en) (so I don't have to repeat myself over and again). The topics you asked for are discussed in [F-Droid for advanced users and developers](https://android.izzysoft.de/articles/named/fdroid-intro-2?lang=en) – to link you directly to the appropriate chapter: [For developers: the process of integrating an app with F-Droid](https://android.izzysoft.de/articles/named/fdroid-intro-2?lang=en#rfp).

**Comment by opyh** [comment]
Thanks for your comments so far! I'm sorry we don’t have the resources for this, so this is a polite 'no'. The app is mostly just a webview container without fancy native extra features, so F-Droid users can just pin the website to their home screen - it will behave the same.
